coverage:
  status:
    project:
      default:
        target: "80"
        threshold: "0"
        strict: "no"
        patch: "yes"
  patch:
    default:
      target: "0"
      threshold: "0"
      strict: "no"
notify:
  require_ci_to_pass: yes
